Repository Akanksha810/Bug-Tracking-Project, pull requests merged in 2020-10, with the labels that each got.

#5 Adding the project structure
  BugTrackingProject/WebContent/index.html
  BugTrackingProject/build/classes/com/code/bean/Bug.class
  BugTrackingProject/build/classes/com/code/bean/Developer.class
  BugTrackingProject/build/classes/com/code/bean/Project.class
  BugTrackingProject/build/classes/com/code/bean/ProjectManager.class
  BugTrackingProject/build/classes/com/code/bean/Tester.class
  BugTrackingProject/build/classes/com/code/bean/User.class
  BugTrackingProject/build/classes/com/code/dao/BugTrackDaoImpl.class
  BugTrackingProject/build/classes/com/code/service/BugTrackServiceImpl.class
  BugTrackingProject/build/classes/com/code/servlet/Hello.class
  BugTrackingProject/src/com/code/bean/Bug.java
  BugTrackingProject/src/com/code/bean/Developer.java
  BugTrackingProject/src/com/code/bean/Project.java
  BugTrackingProject/src/com/code/bean/ProjectManager.java
  BugTrackingProject/src/com/code/bean/Tester.java
  BugTrackingProject/src/com/code/bean/User.java
  BugTrackingProject/src/com/code/dao/BugTrackDao.java
  BugTrackingProject/src/com/code/dao/BugTrackDaoImpl.java
  BugTrackingProject/src/com/code/service/BugTrackService.java
  BugTrackingProject/src/com/code/service/BugTrackServiceImpl.java
  BugTrackingProject/src/com/code/servlet/Hello.java
Labels: documentation

#12 Derby DB structure added
  BugTrackDaoImpl.java
  BugTracking derby.txt
  DBUtil.java
Labels: database

#13 Implemented ImportUsers from json file feature
  BugTrackingProject/WebContent/WEB-INF/web.xml
  BugTrackingProject/WebContent/index.html
  BugTrackingProject/src/com/code/bean/User.java
  BugTrackingProject/src/com/code/dao/BugTrackDao.java
  BugTrackingProject/src/com/code/dao/BugTrackDaoImpl.java
  BugTrackingProject/src/com/code/dao/DBUtil.java
  BugTrackingProject/src/com/code/service/BugTrackService.java
  BugTrackingProject/src/com/code/service/BugTrackServiceImpl.java
  BugTrackingProject/src/com/code/servlet/ImportUsersServlet.java
Labels: enhancement

#15 Adding servlets to display project and bug lists.
  .gitignore.txt
  BugTrackingProject/.classpath
  BugTrackingProject/WebContent/DeveloperBugs.jsp
  BugTrackingProject/WebContent/DeveloperProjects.jsp
  BugTrackingProject/WebContent/PMBugs.jsp
  BugTrackingProject/WebContent/PMProjects.jsp
  BugTrackingProject/WebContent/TesterBugs.jsp
  BugTrackingProject/WebContent/TesterProjects.jsp
  BugTrackingProject/WebContent/WEB-INF/lib/commons-fileupload-1.4.jar
  BugTrackingProject/WebContent/WEB-INF/lib/commons-io-2.8.0.jar
  BugTrackingProject/WebContent/WEB-INF/lib/derby.jar
  BugTrackingProject/WebContent/WEB-INF/lib/gson-2.8.2.jar
  BugTrackingProject/WebContent/index.html
  BugTrackingProject/build/classes/com/code/bean/Bug.class
  BugTrackingProject/build/classes/com/code/bean/Project.class
  BugTrackingProject/build/classes/com/code/bean/User.class
  BugTrackingProject/build/classes/com/code/dao/BugTrackDao.class
  BugTrackingProject/build/classes/com/code/dao/BugTrackDaoImpl.class
  BugTrackingProject/build/classes/com/code/dao/DBUtil.class
  BugTrackingProject/build/classes/com/code/service/BugTrackService.class
  BugTrackingProject/build/classes/com/code/service/BugTrackServiceImpl.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayDeveloperBugsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayDeveloperProjectsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayPMBugsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayPMProjectsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayTesterBugsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/DisplayTesterProjectsServlet.class
  BugTrackingProject/build/classes/com/code/servlet/ImportUsersServlet$1.class
  BugTrackingProject/build/classes/com/code/servlet/ImportUsersServlet.class
  BugTrackingProject/src/com/code/bean/Bug.java
  BugTrackingProject/src/com/code/bean/Project.java
  BugTrackingProject/src/com/code/bean/User.java
  BugTrackingProject/src/com/code/dao/BugTrackDao.java
  BugTrackingProject/src/com/code/dao/BugTrackDaoImpl.java
  BugTrackingProject/src/com/code/dao/DBUtil.java
  BugTrackingProject/src/com/code/service/BugTrackService.java
  BugTrackingProject/src/com/code/service/BugTrackServiceImpl.java
  BugTrackingProject/src/com/code/servlet/DisplayDeveloperBugsServlet.java
  BugTrackingProject/src/com/code/servlet/DisplayDeveloperProjectsServlet.java
  BugTrackingProject/src/com/code/servlet/DisplayPMBugsServlet.java
  BugTrackingProject/src/com/code/servlet/DisplayPMProjectsServlet.java
  BugTrackingProject/src/com/code/servlet/DisplayTesterBugsServlet.java
  BugTrackingProject/src/com/code/servlet/DisplayTesterProjectsServlet.java
Labels: enhancement

#19 Project and Bug List display
  BugTrackingProject v1.0/WebContent/DeveloperBugs.jsp
  BugTrackingProject v1.0/WebContent/DeveloperProjects.jsp
  BugTrackingProject v1.0/WebContent/META-INF/MANIFEST.MF
  BugTrackingProject v1.0/WebContent/PMBugs.jsp
  BugTrackingProject v1.0/WebContent/PMProjects.jsp
  BugTrackingProject v1.0/WebContent/TesterBugs.jsp
  BugTrackingProject v1.0/WebContent/TesterProjects.jsp
  BugTrackingProject v1.0/WebContent/WEB-INF/lib/commons-fileupload-1.4.jar
  BugTrackingProject v1.0/WebContent/WEB-INF/lib/commons-io-2.8.0.jar
  BugTrackingProject v1.0/WebContent/WEB-INF/lib/derby.jar
  BugTrackingProject v1.0/WebContent/WEB-INF/lib/gson-2.8.2.jar
  BugTrackingProject v1.0/WebContent/WEB-INF/web.xml
  BugTrackingProject v1.0/WebContent/bug_DontUseNow.jsp
  BugTrackingProject v1.0/WebContent/index.html
  BugTrackingProject v1.0/WebContent/project_DontUseNow.jsp
  BugTrackingProject v1.0/src/com/code/bean/Bug.java
  BugTrackingProject v1.0/src/com/code/bean/Developer.java
  BugTrackingProject v1.0/src/com/code/bean/Project.java
  BugTrackingProject v1.0/src/com/code/bean/ProjectManager.java
  BugTrackingProject v1.0/src/com/code/bean/Tester.java
  BugTrackingProject v1.0/src/com/code/bean/User.java
  BugTrackingProject v1.0/src/com/code/dao/BugTrackDao.java
  BugTrackingProject v1.0/src/com/code/dao/BugTrackDaoImpl.java
  BugTrackingProject v1.0/src/com/code/dao/DBUtil.java
  BugTrackingProject v1.0/src/com/code/exception/UserNotFoundException.java
  BugTrackingProject v1.0/src/com/code/service/BugTrackService.java
  BugTrackingProject v1.0/src/com/code/service/BugTrackServiceImpl.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayDeveloperBugsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayDeveloperProjectsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayPMBugsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayPMProjectsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayProjectServlet_DontUseNow.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayTesterBugsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/DisplayTesterProjectsServlet.java
  BugTrackingProject v1.0/src/com/code/servlet/Hello.java
  BugTrackingProject v1.0/src/com/code/servlet/ImportUsersServlet.java
  BugTrackingProject v1.0/src/com/code/test/BugTesting.java
Labels: enhancement

#20 Fixed Auto Increment Issue
  BugTrackingProject/src/com/code/dao/DBUtil.java
Labels: work in progress

#22 Update BugTracking derby.txt
  BugTracking derby.txt
  v2.0/WebContent/AddNewBug.jsp
  v2.0/WebContent/Developer.jsp
  v2.0/WebContent/DeveloperBugs.jsp
  v2.0/WebContent/DeveloperProjects.jsp
  v2.0/WebContent/META-INF/MANIFEST.MF
  v2.0/WebContent/PMBugs.jsp
  v2.0/WebContent/PMProjects.jsp
  v2.0/WebContent/PMcreateproject.jsp
  v2.0/WebContent/PmAssignDev.jsp
  v2.0/WebContent/ProjectManager.jsp
  v2.0/WebContent/Tester.jsp
  v2.0/WebContent/TesterBugs.jsp
  v2.0/WebContent/TesterProjects.jsp
  v2.0/WebContent/WEB-INF/lib/commons-fileupload-1.4.jar
  v2.0/WebContent/WEB-INF/lib/commons-io-2.8.0.jar
  v2.0/WebContent/WEB-INF/lib/derby.jar
  v2.0/WebContent/WEB-INF/lib/gson-2.8.2.jar
  v2.0/WebContent/WEB-INF/web.xml
  v2.0/WebContent/bug_DontUseNow.jsp
  v2.0/WebContent/header.jsp
  v2.0/WebContent/index.html
  v2.0/WebContent/login.jsp
  v2.0/WebContent/project_DontUseNow.jsp
  v2.0/src/com/code/bean/Bug.java
  v2.0/src/com/code/bean/Developer.java
  v2.0/src/com/code/bean/Project.java
  v2.0/src/com/code/bean/ProjectManager.java
  v2.0/src/com/code/bean/Tester.java
  v2.0/src/com/code/bean/User.java
  v2.0/src/com/code/dao/BugTrackDao.java
  v2.0/src/com/code/dao/BugTrackDaoImpl.java
  v2.0/src/com/code/dao/DBUtil.java
  v2.0/src/com/code/dao/Trial.java
  v2.0/src/com/code/dao/UserDao.java
  v2.0/src/com/code/dao/UserDaoImpl.java
  v2.0/src/com/code/exception/UserNotFoundException.java
  v2.0/src/com/code/service/BugTrackService.java
  v2.0/src/com/code/service/BugTrackServiceImpl.java
  v2.0/src/com/code/service/UserService.java
  v2.0/src/com/code/service/UserServiceImpl.java
  v2.0/src/com/code/servlet/AssignDevServlet.java
  v2.0/src/com/code/servlet/DisplayDeveloperBugsServlet.java
  v2.0/src/com/code/servlet/DisplayDeveloperProjectsServlet.java
  v2.0/src/com/code/servlet/DisplayPMBugsServlet.java
  v2.0/src/com/code/servlet/DisplayPMProjectsServlet.java
  v2.0/src/com/code/servlet/DisplayProjectServlet_DontUseNow.java
  v2.0/src/com/code/servlet/DisplayTesterBugsServlet.java
  v2.0/src/com/code/servlet/DisplayTesterProjectsServlet.java
  v2.0/src/com/code/servlet/GetBugInfoServlet.java
  v2.0/src/com/code/servlet/Hello.java
  v2.0/src/com/code/servlet/ImportUsersServlet.java
  v2.0/src/com/code/servlet/MyLoginServlet.java
  v2.0/src/com/code/servlet/PMAssign.java
  v2.0/src/com/code/servlet/PMCloseBug.java
  v2.0/src/com/code/servlet/PMCreateProject.java
  v2.0/src/com/code/servlet/TempBugServlet.java
  v2.0/src/com/code/test/BugTesting.java
Labels: database

#21 login module
  BugTrackingProject v1.0/src/com/code/servlet/temp.xml
  BugTrackingProject/WebContent/Developer.jsp
  BugTrackingProject/WebContent/ProjectManager.jsp
  BugTrackingProject/WebContent/Tester.jsp
  BugTrackingProject/WebContent/header.jsp
  BugTrackingProject/WebContent/login.jsp
  BugTrackingProject/src/com/code/dao/UserDao.java
  BugTrackingProject/src/com/code/dao/UserDaoImpl.java
  BugTrackingProject/src/com/code/service/UserService.java
  BugTrackingProject/src/com/code/service/UserServiceImpl.java
  BugTrackingProject/src/com/code/servlet/MyLoginServlet.java
Labels: enhancement, work in progress

#28 added registeration v1
  Registration v1/WebContent/Login.html
  Registration v1/WebContent/META-INF/MANIFEST.MF
  Registration v1/WebContent/Registeration.html
  Registration v1/WebContent/WEB-INF/lib/derby.jar
  Registration v1/WebContent/WEB-INF/web.xml
  Registration v1/WebContent/index.html
  Registration v1/WebContent/js/validateRegister.js
  Registration v1/src/com/code/bean/Bug.java
  Registration v1/src/com/code/dao/BugTrackDao.java
  Registration v1/src/com/code/dao/BugTrackDaoImpl.java
  Registration v1/src/com/code/dao/DBUtil.java
  Registration v1/src/com/code/dao/RegisterDao.java
  Registration v1/src/com/code/dao/RegisterDaoImpl.java
  Registration v1/src/com/code/exception/UserNotFoundException.java
  Registration v1/src/com/code/service/BugTrackService.java
  Registration v1/src/com/code/service/BugTrackServiceImpl.java
  Registration v1/src/com/code/service/RegisterService.java
  Registration v1/src/com/code/service/RegisterServiceImpl.java
  Registration v1/src/com/code/servlet/Hello.java
  Registration v1/src/com/code/servlet/RegisterServlet.java
  Registration v1/src/com/code/test/BugTesting.java
Labels: enhancement, work in progress
